change dynamic selector styles
Eyhenij/rt-tools pull request #112
Opened 2024-10-31 17:19 UTC by treble3d

2024-10-31 23:40 UTC, Eyhenij requested changes

2024-10-31 23:40 UTC, Eyhenij commented on projects/tools/src/lib/ui-kit/dynamic-selectors/components/dynamic-selector/rtui-dynamic-selector.component.html
> +        @if (!entitiesToSelect()?.length && !selectedEntities().length && !searchTerm()) {
давай заведём ещё одну переменную с computed сигналом, назовём например `isPlaceholderShown`, ну и можно так написать `!(entitiesToSelect()?.length || selectedEntities().length || searchTerm())`

2024-10-31 23:40 UTC, Eyhenij commented on projects/tools/src/lib/ui-kit/dynamic-selectors/strories/component/selector/test-selector.component.html
> +                <div rtElem="item-control-label">Label</div>
выглядит так что item-control должен быть самостоятельным блоком

2024-11-01 07:51 UTC, treble3d commented on projects/tools/src/lib/ui-kit/dynamic-selectors/components/dynamic-selector/rtui-dynamic-selector.component.html
> +        @if (!entitiesToSelect()?.length && !selectedEntities().length && !searchTerm()) {
поправил

2024-11-01 07:51 UTC, treble3d commented on projects/tools/src/lib/ui-kit/dynamic-selectors/strories/component/selector/test-selector.component.html
> +                <div rtElem="item-control-label">Label</div>
завел тикет

2024-11-01 07:55 UTC, Eyhenij approved these changes

2024-11-01 07:55 UTC, merged