Feature/implement logic for copy button alignment
Eyhenij/rt-tools pull request #156
Opened 2024-12-29 15:56 UTC by DenHelloWorld

2024-12-30 15:21 UTC, Eyhenij requested changes

2024-12-30 15:21 UTC, Eyhenij commented on projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.ts
> +        if (copyBtnAlign === 'left') {
if (copyBtnAlign) {
            return copyBtnAlign;
        }

2024-12-30 15:21 UTC, Eyhenij commented on projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.ts
> +        return align === 'right' ? 'left' : 'right';
выглядит оч странно
почему возвращаем наоборот?

2024-12-30 15:24 UTC, DenHelloWorld commented on projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.ts
> +        return align === 'right' ? 'left' : 'right';
Потому что мы смотрим на расположение текста, если текст справа, то кнопка слева

2025-01-03 04:08 UTC, Eyhenij approved these changes

2025-01-03 04:08 UTC, merged